// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TA9_Graph_DB_Managment.SharedDb;

#nullable disable

namespace TA9_Graph_DB_Managment.Migrations
{
    [DbContext(typeof(GraphDbContext))]
    [Migration("20241126134100_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TA9_HomeAssignment_serviceB.Shaphes.Edge", b =>
                {
                    b.Property<string>("EdgeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Node1_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Node2_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EdgeId");

                    b.ToTable("Edges");
                });

            modelBuilder.Entity("TA9_HomeAssignment_serviceB.Shaphes.Node", b =>
                {
                    b.Property<string>("NodeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Data")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("Neighbors")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("NodeId");

                    b.ToTable("Nodes");
                });
#pragma warning restore 612, 618
        }
    }
}
